

@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhaW9AZ21haWwuY29tIiwiaWQiOiI1ZGFhNTcyMWIzNDM4OTdmYzAzMTVmMzkiLCJuYW1lIjoiQ2FpbyIsImlhdCI6MTU3MTUzMTQyMn0.P2fcGZSZfEECtXInuWrBbSAuKFYNTy50Kzl72NzPt4s

GET http://localhost:3000/auth/login http/1.1
ngstackauth : {{token}}



###
GET http://localhost:3000/posts/5dae925424fcf166a0e87e76/comments http/1.1
ngstackauth : {{token}}


###
POST http://localhost:3000/posts/5dad0bdf4ed73e3a6086f4b2/comments http/1.1
ngstackauth : {{token}}
Content-Type: application/json

{
    "content":"Wait Comment on Tuesday 22_5",
    "owner":"John Vallon By Update Guy",
    "like":8
}

###
PUT http://localhost:3000/posts/5dad0bdf4ed73e3a6086f4b2/comments/5dad0f92a896688758101a47 http/1.1
ngstackauth : {{token}}

Content-Type: application/json
 
{
    "content":"Realy Baby ",
    "owner":"John Vallon By Update Guy"
}


###
PATCH http://localhost:3000/posts/5dad0bdf4ed73e3a6086f4b2/comments/5dae20c2921a3f63b61e80da/like http/1.1
ngstackauth : {{token}}
Content-Type: application/json


###
DELETE http://localhost:3000/posts/5dad0bdf4ed73e3a6086f4b2/comments/5dad0f92a896688758101a47 http/1.1
Content-Type: application/json


