
Get http://localhost:3000/test http/1.1

###
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpzQGdtYWlsLmNvbSIsImlhdCI6MTU3MTQzNzg4M30.CaclSMbMjYM0QA2zqk5-ongdIA4KBx7xM29RGK72T-o

GET http://localhost:3000/auth http/1.1
ngstackauth : {{token}}



###
GET http://localhost:3000/posts/5dab4bc5c3b5510290ff7460/comments http/1.1


###
POST http://localhost:3000/posts/5dab4bc5c3b5510290ff7460/comments http/1.1
Content-Type: application/json

{
    "content":"message ",
    "owner":"Caio Hoffman"
}

###
GET http://localhost:3000/posts/123/comments/5daa815ab40582874da722a3 http/1.1


###
DELETE http://localhost:3000/posts/123/comments/5daa81d5c88c9587793d259f http/1.1


###
PUT  http://localhost:3000/posts/123/comments/5daa81af28ef4f876faadfc6 http/1.1
Content-Type: application/json
 
{
    "content":"New Content for you"
}
