@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpzQGdtYWlsLmNvbSIsImlhdCI6MTU3MTUwNTkwMn0.uxHY244DCJtGGOlUSZKvoN6OYi5_VikZk0GFmQUarxI
###Get Token
Get http://localhost:3000/test http/1.1

### Get All Posts
get http://localhost:3000/posts/posts http/1.1
ngstackauth : {{token}}

### Get All Homes
get http://localhost:3000/posts/homes http/1.1
ngstackauth : {{token}}

### Get Homes Paged
get http://localhost:3000/posts/homes/2 http/1.1
ngstackauth : {{token}}

### Get Post By Id
get http://localhost:3000/posts/5dab4c4d56ddc42924e634d7 http/1.1
ngstackauth : {{token}}

### Create New Post
POST http://localhost:3000/posts http/1.1
ngstackauth : {{token}}
Content-Type: application/json

{
    "title":"my 10 post",
    "tags":["sport", "tech"],
    "owner":{ "name": "Ali", "badge": 123}
}

### Delete a Post
delete http://localhost:3000/posts/5dab60dc56dfe31f58927352 http/1.1
ngstackauth : {{token}}

###
get http://localhost:3000/posts/1/comments http/1.1




