
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpzQGdtYWlsLmNvbSIsImlhdCI6MTU3MTUwNTkwMn0.uxHY244DCJtGGOlUSZKvoN6OYi5_VikZk0GFmQUarxI
POST http://localhost:3000/users/ HTTP/1.1
Content-Type: application/json
ngstackauth : {{token}}

{
    "email" : "mi@muum.edu",
    "name":"miki",
    "password" : "321",
    "picture":"dshajfhf"
}
###

GET http://localhost:3000/users/5dae5f9a8d728c6c6feb01d2 HTTP/1.1
Content-Type: application/json
ngstackauth : {{token}}


# ###
# PATCH http://localhost:3000/users/5dae5f9a8d728c6c6feb01d2 HTTP/1.1
# Content-Type: application/json
# ngstackauth : {{token}}


# {
#     "name":"aron"
# }
# ###
########

DELETE  http://localhost:3000/delete/5dae5f9a8d728c6c6feb01d2 HTTP/1.1
Content-Type: application/json
ngstackauth : {{token}}


{
    "content" : " DELETE "
}


############
PUT  http://localhost:3000/users/5dae5f9a8d728c6c6feb01d2 HTTP/1.1
Content-Type: application/json
ngstackauth : {{token}}


{
    "picture" : "cddfda",
    "name":"Caio",
    "password" : 123
}

###
Get http://localhost:3000/test http/1.1