POST http://localhost:3000/users/userPost HTTP/1.1
Content-Type: application/json

{
    "content" : " new user to regisiter"
}
###

GET http://localhost:3000/users/5dab4c4d56ddc42924e634d7 HTTP/1.1
Content-Type: application/json

{
    "content" : " new user to regisiter"
}



###
PATCH http://localhost:3000/user/patch HTTP/1.1
Content-Type: application/json

{
    "content" : " user partial update"
}
###
DELETE http://localhost:3000/users/5dab60dc56dfe31f58927352 HTTP/1.1
Content-Type: application/json

{
    "content" : " DELETE "
}